/* Generated by Yosys 0.68+136 (git sha1 c30457480-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

module led_chaser(clk, rst_n, en, led);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [3:0] led;
  reg [3:0] led;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  reg [24:0] tick;
  assign _065_ = ~tick[0];
  assign _028_ = tick[1] & tick[0];
  assign _029_ = tick[2] & _028_;
  assign _030_ = tick[3] & _029_;
  assign _031_ = tick[4] & _030_;
  assign _032_ = tick[5] & _031_;
  assign _033_ = tick[6] & _032_;
  assign _034_ = tick[7] & _033_;
  assign _035_ = tick[8] & _034_;
  assign _036_ = tick[9] & _035_;
  assign _037_ = tick[10] & _036_;
  assign _038_ = tick[11] & _037_;
  assign _039_ = tick[12] & _038_;
  assign _040_ = tick[13] & _039_;
  assign _041_ = tick[14] & _040_;
  assign _042_ = tick[15] & _041_;
  assign _043_ = tick[16] & _042_;
  assign _044_ = tick[17] & _043_;
  assign _045_ = tick[19] & tick[20];
  assign _046_ = tick[18] & tick[21];
  assign _047_ = _045_ & _046_;
  assign _048_ = _044_ & _047_;
  assign _049_ = tick[22] & _048_;
  assign _050_ = ~(tick[23] & _049_);
  assign _080_ = tick[23] ^ _049_;
  assign _051_ = _032_ & ~(tick[6]);
  assign _052_ = tick[11] & ~(tick[17]);
  assign _053_ = ~(tick[9] | tick[8]);
  assign _054_ = tick[16] & ~(tick[23]);
  assign _055_ = _052_ & _054_;
  assign _056_ = _053_ & _055_;
  assign _057_ = tick[24] & tick[13];
  assign _058_ = tick[12] & ~(tick[7]);
  assign _059_ = _057_ & _058_;
  assign _060_ = tick[22] & tick[14];
  assign _061_ = ~(tick[15] | tick[10]);
  assign _062_ = _060_ & _061_;
  assign _063_ = _059_ & _062_;
  assign _064_ = _047_ & _063_;
  assign _002_ = _056_ & _064_;
  assign _003_ = ~(_051_ & _002_);
  assign _004_ = tick[22] ^ _048_;
  assign _005_ = _056_ & _063_;
  assign _006_ = _047_ & _005_;
  assign _007_ = ~(_051_ & _006_);
  assign _079_ = _004_ & _007_;
  assign _008_ = tick[18] & _044_;
  assign _009_ = _045_ & _008_;
  assign _010_ = tick[21] | _009_;
  assign _011_ = _048_ | ~(_003_);
  assign _078_ = _010_ & ~(_011_);
  assign _012_ = tick[19] & _008_;
  assign _013_ = tick[20] | _012_;
  assign _014_ = _003_ & ~(_009_);
  assign _077_ = _013_ & _014_;
  assign _015_ = tick[19] | _008_;
  assign _016_ = _007_ & _015_;
  assign _075_ = _016_ & ~(_012_);
  assign _017_ = tick[18] | _044_;
  assign _018_ = _007_ & _017_;
  assign _074_ = _018_ & ~(_008_);
  assign _073_ = tick[17] ^ _043_;
  assign _019_ = tick[16] ^ _042_;
  assign _072_ = _007_ & _019_;
  assign _071_ = tick[15] ^ _041_;
  assign _020_ = tick[14] ^ _040_;
  assign _070_ = _007_ & _020_;
  assign _021_ = tick[13] ^ _039_;
  assign _069_ = _007_ & _021_;
  assign _022_ = tick[12] ^ _038_;
  assign _068_ = _007_ & _022_;
  assign _023_ = tick[11] ^ _037_;
  assign _067_ = _007_ & _023_;
  assign _066_ = tick[10] ^ _036_;
  assign _089_ = tick[9] ^ _035_;
  assign _088_ = tick[8] ^ _034_;
  assign _087_ = tick[7] ^ _033_;
  assign _024_ = tick[6] ^ _032_;
  assign _086_ = _003_ & _024_;
  assign _085_ = tick[5] ^ _031_;
  assign _084_ = tick[4] ^ _030_;
  assign _083_ = tick[3] ^ _029_;
  assign _082_ = tick[2] ^ _028_;
  assign _076_ = tick[1] ^ tick[0];
  assign _025_ = ~(led[3] | led[2]);
  assign _026_ = led[0] & ~(led[1]);
  assign _001_ = _025_ & _026_;
  assign _000_ = en & ~(_003_);
  assign _027_ = ~(tick[24] ^ _050_);
  assign _081_ = _003_ & _027_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) led[0] <= 1'h0;
    else if (_000_) led[0] <= led[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) led[1] <= 1'h0;
    else if (_000_) led[1] <= led[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) led[2] <= 1'h0;
    else if (_000_) led[2] <= led[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) led[3] <= 1'h1;
    else if (_000_) led[3] <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[0] <= 1'h0;
    else if (en) tick[0] <= _065_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[1] <= 1'h0;
    else if (en) tick[1] <= _076_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[2] <= 1'h0;
    else if (en) tick[2] <= _082_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[3] <= 1'h0;
    else if (en) tick[3] <= _083_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[4] <= 1'h0;
    else if (en) tick[4] <= _084_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[5] <= 1'h0;
    else if (en) tick[5] <= _085_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[6] <= 1'h0;
    else if (en) tick[6] <= _086_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[7] <= 1'h0;
    else if (en) tick[7] <= _087_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[8] <= 1'h0;
    else if (en) tick[8] <= _088_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[9] <= 1'h0;
    else if (en) tick[9] <= _089_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[10] <= 1'h0;
    else if (en) tick[10] <= _066_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[11] <= 1'h0;
    else if (en) tick[11] <= _067_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[12] <= 1'h0;
    else if (en) tick[12] <= _068_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[13] <= 1'h0;
    else if (en) tick[13] <= _069_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[14] <= 1'h0;
    else if (en) tick[14] <= _070_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[15] <= 1'h0;
    else if (en) tick[15] <= _071_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[16] <= 1'h0;
    else if (en) tick[16] <= _072_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[17] <= 1'h0;
    else if (en) tick[17] <= _073_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[18] <= 1'h0;
    else if (en) tick[18] <= _074_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[19] <= 1'h0;
    else if (en) tick[19] <= _075_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[20] <= 1'h0;
    else if (en) tick[20] <= _077_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[21] <= 1'h0;
    else if (en) tick[21] <= _078_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[22] <= 1'h0;
    else if (en) tick[22] <= _079_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[23] <= 1'h0;
    else if (en) tick[23] <= _080_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tick[24] <= 1'h0;
    else if (en) tick[24] <= _081_;
endmodule
